<?php

namespace Coff\Hellfire\Server;

use Coff\OneWire\Client\AsyncW1Client;
use Coff\OneWire\Server\Server;

class HellfireServer extends Server
{
    /**
     * @var AsyncW1Client
     */
    protected $w1Client;

    /**
     * PDO storage for keeping sensors' readings and control devices' states
     * @var
     */
    protected $storage;

    /**
     * @var \PDO
     */
    protected $pdo;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->w1Client->init();

    }

    public function each()
    {
        $this->w1Client->update();
    }

    public function everyMinute()
    {
        /**
         * Store sensors readings
         */



    }

}
