<?php

namespace Coff\Hellfire\Command;

use Coff\Hellfire\Application\HellfireApplication;
use Pimple\Container;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Command
 *
 * Basic Hellfire Command with Pimple container attached.
 */
abstract class Command extends \Symfony\Component\Console\Command\Command
{
    protected $logFilename = 'hellfire-common.log';
    protected $container;

    /**
     * Returns pimple DI container
     *
     * @return Container
     */
    public function getContainer() {

        return $this->container;
    }

    /**
     * @throws \ReflectionException
     */
    public static function getBootstrapClass()
    {
        return static::class . 'Bootstrap';
    }

    public function getLogFilename() {
        return $this->logFilename;
    }

    public function run(InputInterface $input, OutputInterface $output)
    {
        $bootstrapClass = self::getBootstrapClass();
        $bootstrap = new $bootstrapClass(new Container());
        $bootstrap->init();

        $this->container = $bootstrap->getContainer();

        $this->container['running_command'] = $this;

        return parent::run($input, $output); // TODO: Change the autogenerated stub
    }
}
