<?php

namespace Coff\Hellfire\System;

use Coff\DataSource\DataSource;
use Coff\Hellfire\ComponentArray\DataSourceArray;
use Coff\Hellfire\Relay\Relay;
use Hellfire\Servo\AnalogServo;

class BoilerSystem extends System
{
    use PumpTrait;
    use SensorArrayTrait;

    const
        SENSOR_HIGH         = 'high',
        SENSOR_LOW          = 'low';

    const
        STATE_COLD          = 'cold',
        STATE_WARMING       = 'warming',
        STATE_BURNING       = 'burning',
        STATE_COOLING       = 'cooling',
        STATE_OVERHEAT      = 'overheat';



    /**
     * @var DataSource
     */
    protected $exhaustSensor;

    /**
     * @var AirIntakeSystem
     */
    protected $airIntake;

    public function process() {
        switch ($this->state) {
            case self::STATE_COLD:

                break;

            case self::STATE_WARMING:

                break;

            case self::STATE_BURNING:
                break;

            case self::STATE_COOLING:
                break;

            case self::STATE_OVERHEAT:
                break;
        }
    }

    public function setState($state)
    {
        switch ($state) {
            case self::STATE_COLD:
                /**
                 * - open air intake for ventilation
                 * - disable water-pump
                 */

                $this->pump->off();

                break;

            case self::STATE_WARMING:
                /**
                 * - open air intake to provide good airflow
                 * - enable water-pump
                 */

                $this->pump->on();
                break;

            case self::STATE_BURNING:
                /**
                 *
                 */

                // just in case
                $this->pump->on();
                break;

            case self::STATE_COOLING:
                /**
                 * - disable water-pump to limit heat leakage
                 */

                $this->pump->off();
                break;

            case self::STATE_OVERHEAT:
                /**
                 * - enable water-pump to get rid of that excess heat
                 * - fully close air intake
                 */

                $this->pump->on();
                break;
        }

        return parent::setState($state); // TODO: Change the autogenerated stub
    }

    /**
     * Sets exhaust gases thermocouple sensor
     *
     * @param DataSource $sensor
     * @return $this
     */
    public function setExhaustSensor(DataSource $sensor) {
        $this->exhaustSensor = $sensor;

        return $this;
    }

    public function setAirIntake(AirIntakeSystem $airIntake) {
        $this->airIntake = $airIntake;

        return $this;
    }

    public function getAirIntake() {
        return $this->airIntake;
    }
}
