<?php

namespace Coff\Hellfire\Heater;

use Coff\DataSource\DataSource;
use Coff\Hellfire\ComponentArray\DataSourceArray;
use Coff\Hellfire\Relay\Relay;

class Boiler extends Element
{
    const
        STATE_COLD          = 'cold',
        STATE_WARMING       = 'warming',
        STATE_BURNING       = 'burning',
        STATE_COOLING       = 'cooling',
        STATE_OVERHEATING   = 'overheating';

    /**
     * @var DataSourceArray
     */
    protected $sensorArray;

    /**
     * @var DataSource
     */
    protected $exhaustSensor;

    protected $airIntakeController;

    /**
     * @var Relay
     */
    protected $pump;

    public function process() {
        switch ($this->state) {
            case self::STATE_COLD:

                break;

            case self::STATE_WARMING:

                break;

            case self::STATE_BURNING:
                break;

            case self::STATE_COOLING:
                break;

            case self::STATE_OVERHEATING:
                break;
        }
    }

    public function setState($state)
    {
        switch ($state) {
            case self::STATE_COLD:
                /**
                 * - open air intake for ventilation
                 * - disable water-pump
                 */

                $this->pump->off();

                break;

            case self::STATE_WARMING:
                /**
                 * - open air intake to provide good airflow
                 * - enable water-pump
                 */

                $this->pump->on();
                break;

            case self::STATE_BURNING:
                /**
                 *
                 */

                // just in case
                $this->pump->on();
                break;

            case self::STATE_COOLING:
                /**
                 * - disable water-pump to limit heat leakage
                 */

                $this->pump->off();
                break;

            case self::STATE_OVERHEATING:
                /**
                 * - enable water-pump to get rid of heat
                 * - fully close air intake
                 */

                $this->pump->off();
                break;
        }

        return parent::setState($state); // TODO: Change the autogenerated stub
    }

    /**
     * Sets pump that sends boiler's heat to buffer tank.
     * @param $pump
     * @return $this
     */
    public function setPump($pump) {
        $this->pump = $pump;

        return $this;
    }

    /**
     * Sets sensor array with HI and LO sensor for boiler
     *
     * @param DataSourceArray $array
     * @return $this
     */
    public function setSensorArray(DataSourceArray $array) {
        $this->sensorArray = $array;

        return $this;
    }

    /**
     * Sets exhaust gases thermocouple sensor
     *
     * @param DataSource $sensor
     * @return $this
     */
    public function setExhaustSensor(DataSource $sensor) {
        $this->exhaustSensor = $sensor;

        return $this;
    }
}
