<?php

namespace Coff\Hellfire\Event;

use Coff\Hellfire\Buzzer;
use Coff\Hellfire\BuzzerNotes;

class HeaterEvent extends Event
{
    const
        PUMP_ENABLED    = 'heater.pump_enabled',
        PUMP_DISABLED   = 'heater.pump_disabled';

    public function onDispatch($eventName)
    {
        /** @var Buzzer $buzzer */
        $buzzer = $this->getContainer()['buzzer'];

        $notes = new BuzzerNotes();

        switch ($eventName) {
            case self::PUMP_ENABLED:
                $notes->add([1,1,0,1,0]);
                break;

            case self::PUMP_DISABLED:
                $notes->add([1,1,0,1,0,1]);
                break;
        }

        $buzzer
            ->setNotes($notes)
            ->play();

        return parent::onDispatch($eventName); // TODO: Change the autogenerated stub
    }
}
